---
title: "Lessons"
output:
  html_document:
    theme: united
---

# Rough lesson plans


## Week 1, Day 1

Before class:

* Install git
* Get GitHub account
* Sign up for [GitHub Education Pack](https://education.github.com/pack)
* Install GitKraken


During class:

1. Go over course outline and syllabus
2. Set aside some time in the beginning to finish and troubleshoot above.
3. Go over git and GitHub basics: what are they, why useful, etc.
  * take from the beginning of
    <https://www.lucasnell.com/resources/github-rstudio/>
  * another good source of info: <https://happygitwithr.com/>
4. Fork template repo and clone to local machine:
   <https://github.com/lucasnell/pranga-template>
5. Go over Markdown format:
   <https://www.markdownguide.org/basic-syntax/>
6. Students edit `README.md` in their new repo, commit, and push to GitHub
7. If doing solitary projects - 15 minutes to hash out their ideas and talk 
   to us about their ideas.




## Week 1, Day 2

Before class:

* Figure out project idea
* Finish editing top-level README
* Add files (not data unless you have permission!) to your repo


During class:

1. Take time in the beginning to chat about projects.

2. File management
   base on fig. 2 from Griffon's paper: <https://arxiv.org/pdf/2210.02593.pdf>,
   [BES Guide to Reproducible Code](https://www.britishecologicalsociety.org/wp-content/uploads/2019/06/BES-Guide-Reproducible-Code-2019.pdf),
   [BES Guide to File Management](https://www.britishecologicalsociety.org/wp-content/uploads/2019/06/BES-Guide-Data-Management-2019.pdf),
   and `gameofclones-data`

3. Creating a workflow

[BES Guide to Reproducible Code](https://www.britishecologicalsociety.org/wp-content/uploads/2019/06/BES-Guide-Reproducible-Code-2019.pdf)

Figure 1 from <https://arxiv.org/pdf/2210.02593.pdf>


For next class: Plan your workflow for your project




## Week 1, Day 3


From last week: Review workflows as a class


1. Data management
   * METADATA
   * <https://guides.lib.unc.edu/metadata/best-practices>
   * <https://datamanagement.hms.harvard.edu/collect-analyze/documentation-metadata>
   * <https://datadryad.org/stash/best_practices>

How can we organize your data better?

Create data plans in class and go over them




## Week 2, Day 1

1. R basics

2. Intro to functional coding
<https://www.lucasnell.com/resources/functionalr/>,
<https://adv-r.hadley.nz/fp.html>



## Week 2, Day 2


1. Sourcing files

2. Creating packages

How can this be incorporated into your workflow?



## Week 2, Day 3

Data visualization



## Week 3, Day 1

Creating reports using Rmarkdown


## Week 3, Day 2

Maybe leave open to help them create their reports?



## Week 3, Day 3

Presentations of projects from GitHub 
